// <auto-generated />
// Generated from OData $metadata (v3) - 2026-02-11T09:19:29.750211Z
using System;
using System.Collections.Generic;
using Simple.OData.Client;

namespace TD.Technical.ODataClient.ConfigModel;
#nullable enable
public class INDIC_SETTINGS
{
    public int SETTINGID { get; set; }
    public int USERINDICATORID { get; set; }
    public string SETTINGVALUE { get; set; } = string.Empty;
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class INDIC_SETTING_PRES_LABO
{
    public int LABOID { get; set; }
}

public class INDIC_SETTING_FILTERS
{
}

public class INDIC_SETTING_PRES
{
}

public class INDICATOR_TYPES
{
    public int INDICATORTYPEID { get; set; }
    public Guid IDENTIFIER { get; set; }
    public string? NAME { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class USER_INDICATORS
{
    public int USERINDICATORID { get; set; }
    public string USERID { get; set; } = string.Empty;
    public int INDICATORTYPEID { get; set; }
    public string? NAME { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class PARAM_VALUES_DEFAULT
{
    public int PARAMVALUESDEFAULTID { get; set; }
    public int? CLASSTYPE { get; set; }
    public string? PARAMID { get; set; }
    public int? PARAMTYPE { get; set; }
    public string? MINIMUMVAL { get; set; }
    public string? MAXIMUMVAL { get; set; }
    public string? DEFAULTVAL { get; set; }
}

public class PARAM_VALUES_SECTION
{
    public int PARAMSSECTIONID { get; set; }
    public string TEXTREF { get; set; } = string.Empty;
    public int SECTIONRANK { get; set; }
    public int? FATHERSECTIONID { get; set; }
}

public class PARAM_VALUES_VIEWS
{
    public int PARAMVALUESVIEWID { get; set; }
    public int PARAMVALUESDEFAULTID { get; set; }
    public int PARAMSSECTIONID { get; set; }
    public int PARAMRANK { get; set; }
    public byte? HIDDEN { get; set; }
    public string? UPDPRIVILEGES { get; set; }
}

public class DEFAULT_FUNCTIONS
{
    public int DEFAULTFUNCTIONID { get; set; }
    public string TEXTREF { get; set; } = string.Empty;
    public byte? FUNCTYPE { get; set; }
    public string? FUNCALIAS { get; set; }
    public string? FUNCSHORTCUT { get; set; }
    public string? DLLNAME { get; set; }
    public string? DLLARGUMENT { get; set; }
    public string? PRIVILEGES { get; set; }
}

public class DEFFUNCTIONS_PRESENTATION
{
    public int DEFAULTFUNCTIONID { get; set; }
    public int DEFFUNCTIONSECTIONID { get; set; }
    public int? FUNCRANK { get; set; }
    public byte? HIDDEN { get; set; }
}

public class DEFFUNCTIONS_SECTIONS
{
    public int DEFFUNCTIONSECTIONID { get; set; }
    public string TEXTREF { get; set; } = string.Empty;
    public int SECTIONRANK { get; set; }
    public int? FATHERSECTIONID { get; set; }
    public string? PRIVILEGES { get; set; }
}

public class SAMPLES_CHRONOID
{
    public int SAMPLEID { get; set; }
    public int STNID { get; set; }
    public string CHRONOID { get; set; } = string.Empty;
    public string? LOGUSERID { get; set; }
    public DateTime? LOGDATE { get; set; }
}

public class DICT_DEVICE_PARAMETERS
{
    public int DEVPARAMID { get; set; }
    public int DEVICEID { get; set; }
    public int? DEVPARAMTYPE { get; set; }
    public string? DEVPARAMNAME { get; set; }
    public string? DEVPARAMVALUE { get; set; }
    public int? DEVPARAMDATAFLOW { get; set; }
    public int? DEVPARAMGROUP { get; set; }
    public short? DEVPARAMUPDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SIMPLE_NON_CONFORMITY
{
    public int NCID { get; set; }
    public Guid NCTYPE { get; set; }
    public string NCTEXT { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
}

public class SP_REQUESTS_NC
{
    public int NCID { get; set; }
    public string SP_ACCESSNUMBER { get; set; } = string.Empty;
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SP_TUBES_NC
{
    public int NCID { get; set; }
    public string TUBENB { get; set; } = string.Empty;
    public string DATA_BASE { get; set; } = string.Empty;
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class EVENTLISTS
{
    public int EVENTLISTID { get; set; }
    public byte EVENTLISTTYPE { get; set; }
    public string EVENTLISTSESSION { get; set; } = string.Empty;
    public DateTime EVENTLISTTIME { get; set; }
    public string EVENTLISTDATA { get; set; } = string.Empty;
    public string? EVENTLISTDETAILS { get; set; }
}

public class USER_DB_SESSIONS
{
    public string ID { get; set; } = string.Empty;
    public string USERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public int? SIDDB { get; set; }
}

public class SYSSESSIONID
{
    public int SIDDB { get; set; }
}

public class DICT_WEEK_DAYS
{
    public int DAYID { get; set; }
    public int WEEKID { get; set; }
    public byte DAYORDER { get; set; }
    public DateTime STARTINGTIME { get; set; }
    public DateTime ENDINGTIME { get; set; }
    public byte SHIFTTYPE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_TYPICAL_WEEKS
{
    public int WEEKID { get; set; }
    public DateTime? STARTINGDATE { get; set; }
    public DateTime? ENDINGDATE { get; set; }
    public int? SHIFTSORDER { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_TYPICAL_WEEKS_DPTS
{
    public int WEEKID { get; set; }
    public int DEPARTMENTID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_TYPICAL_WEEKS_LABOS
{
    public int WEEKID { get; set; }
    public int LABOID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class RESPONSIBLES
{
    public int SHIFTID { get; set; }
    public string USERID { get; set; } = string.Empty;
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SHIFT_DEFINITION
{
    public int SHIFTID { get; set; }
    public int DAYID { get; set; }
    public DateTime STARTINGDATETIME { get; set; }
    public DateTime ENDINGDATETIME { get; set; }
    public byte SHIFTTYPE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class ALERT_DISTRIBUTION
{
    public int ALERTDISTRIBUTIONID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class ALERT_EVENTS
{
    public int ALERTEVENTID { get; set; }
    public DateTime? SENDDATE { get; set; }
    public DateTime? ACKDATE { get; set; }
    public DateTime? ENDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class COUNTERS_VALUES
{
    public int COUNTERID { get; set; }
    public DateTime COMPUTETIME { get; set; }
    public int COUNTERVALUE { get; set; }
    public int? COUNTERCOLOR { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_ALERTS
{
    public int ALERTID { get; set; }
    public int? DISTRIBUTIONID { get; set; }
    public string ALERTCODE { get; set; } = string.Empty;
    public int ALERTCREDATE { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public string? SUBJECT { get; set; }
    public string TEXTTOSEND { get; set; } = string.Empty;
    public byte? SENDINGMODE { get; set; }
    public byte? REQUESTDISTRIBUTION { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_COUNTER_PROPERTIES
{
    public int COUNTERPROPID { get; set; }
    public int COUNTERPROPTYPE { get; set; }
    public string COUNTERPROPVALUE { get; set; } = string.Empty;
    public string? COUNTERPROPSUBVALUE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_COUNTER_THRESHOLDS
{
    public int THRESHOLDID { get; set; }
    public string THRESHOLDTEXT { get; set; } = string.Empty;
    public int THRESHOLDVALUE { get; set; }
    public int THRESHOLDCOLOR { get; set; }
    public string? LOGUSERID { get; set; }
    public DateTime? LOGDATE { get; set; }
}

public class DICT_COUNTERS
{
    public int COUNTERID { get; set; }
    public string COUNTERCODE { get; set; } = string.Empty;
    public int COUNTERCREDATE { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public int TIMERANGE { get; set; }
    public int COUNTINGTYPE { get; set; }
    public byte COUNTINGMODE { get; set; }
    public byte? COUNTINGENABLED { get; set; }
    public int REFRESHTIME { get; set; }
    public int DEFAULTCOLOR { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_DISTRIBUTION_CONTACTS
{
    public int DISTCONTACTID { get; set; }
    public string CONTACTNAME { get; set; } = string.Empty;
    public string? TELEPHON { get; set; }
    public string? EMAIL { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_DISTRIBUTION_LIST
{
    public int DISTRIBUTIONID { get; set; }
    public string DISTRIBUTIONCODE { get; set; } = string.Empty;
    public int DISTRIBUTIONCREDATE { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_DISTRIBUTION_USERS
{
    public string USERID { get; set; } = string.Empty;
    public int DISTRIBUTIONID { get; set; }
    public short CONTACTMODE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class REQUEST_CLINICALNOTES
{
    public int REQUESTID { get; set; }
    public short RANK { get; set; }
    public string USERID { get; set; } = string.Empty;
    public string NOTE { get; set; } = string.Empty;
    public DateTime CREATIONDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class UNIX_MESSAGES
{
    public int ID { get; set; }
    public byte TYPEMSG { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class BINARY_DATA
{
    public int BINARYID { get; set; }
    public int OBJECTLINK { get; set; }
    public int OBJECTTYPE { get; set; }
    public int BINARYTYPE { get; set; }
    public DateTime BINARYDATE { get; set; }
    public string? BINARYMIMETYPE { get; set; }
    public int? BINARYSIZE { get; set; }
    public string? BINARYVALUE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public byte[]? BINARYOBJECT { get; set; }
    public int? ACCESS_CONTROL { get; set; }
}

public class BINARY_PARAMETERS
{
    public int BINARYPARAMID { get; set; }
    public int BINARYID { get; set; }
    public int BINARYPARAMTYPE { get; set; }
    public string? BINARYPARAMNAME { get; set; }
    public string? BINARYPARAMVALUE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SYSCONSTRAINT
{
    public string CONSTRAINTNAME { get; set; } = string.Empty;
    public string TABLENAME { get; set; } = string.Empty;
    public int? CONSTRAINTENABLED { get; set; }
}

public class PROBEREQUESTSWITHPENDINGTEST
{
    public int REQUESTID { get; set; }
    public string ACCESSNUMBER { get; set; } = string.Empty;
    public int REQCREATIONDATE { get; set; }
    public DateTime? REQDATE { get; set; }
    public DateTime? COLLECTIONDATE { get; set; }
    public int PATID { get; set; }
    public string? PATNUMBER { get; set; }
    public string? PATIENTNAME { get; set; }
    public string? PATIENTFIRSTNAME { get; set; }
    public int? SOURCELABOID { get; set; }
    public string? SOURCELABOCODE { get; set; }
    public int? REQDOCID { get; set; }
    public int? DOCID { get; set; }
    public string? DOCCODE { get; set; }
    public string? DOCNAME { get; set; }
    public int? REQLOCID { get; set; }
    public int? LOCID { get; set; }
    public string? LOCCODE { get; set; }
    public string? LOCNAME { get; set; }
    public int REQTESTID { get; set; }
    public int? PRODLABOID { get; set; }
    public string? PRODLABOCODE { get; set; }
    public int PRODDEPTID { get; set; }
    public int PRODTECHGRPID { get; set; }
    public int? PRODSTNID { get; set; }
}

public class PROBEREQUESTSWITHCRITICALTEST
{
    public int REQUESTID { get; set; }
    public string ACCESSNUMBER { get; set; } = string.Empty;
    public int REQCREATIONDATE { get; set; }
    public DateTime? REQDATE { get; set; }
    public DateTime? COLLECTIONDATE { get; set; }
    public int PATID { get; set; }
    public string? PATNUMBER { get; set; }
    public string? PATIENTNAME { get; set; }
    public string? PATIENTFIRSTNAME { get; set; }
    public int? SOURCELABOID { get; set; }
    public string? SOURCELABOCODE { get; set; }
    public string? SOURCELABOSHORTTEXT { get; set; }
    public int? REQDOCID { get; set; }
    public int? DOCID { get; set; }
    public string? DOCCODE { get; set; }
    public string? DOCNAME { get; set; }
    public int? REQLOCID { get; set; }
    public int? LOCID { get; set; }
    public string? LOCCODE { get; set; }
    public string? LOCNAME { get; set; }
    public int REQTESTID { get; set; }
    public int TESTID { get; set; }
    public string TESTCODE { get; set; } = string.Empty;
    public string? TESTSHORTTEXT { get; set; }
    public int? PRODLABOID { get; set; }
    public string? PRODLABOCODE { get; set; }
    public string? PRODLABOSHORTTEXT { get; set; }
    public int PRODDEPTID { get; set; }
    public int PRODTECHGRPID { get; set; }
    public int? PRODSTNID { get; set; }
}

public class PROBEREQUESTSWITHSAMPTOBEREC
{
    public int REQUESTID { get; set; }
    public string ACCESSNUMBER { get; set; } = string.Empty;
    public int REQCREATIONDATE { get; set; }
    public DateTime? REQDATE { get; set; }
    public DateTime? COLLECTIONDATE { get; set; }
    public int PATID { get; set; }
    public string? PATNUMBER { get; set; }
    public string? PATIENTNAME { get; set; }
    public string? PATIENTFIRSTNAME { get; set; }
    public int? SOURCELABOID { get; set; }
    public string? SOURCELABOCODE { get; set; }
    public string? SOURCELABOSHORTTEXT { get; set; }
    public int? REQDOCID { get; set; }
    public int? DOCID { get; set; }
    public string? DOCCODE { get; set; }
    public string? DOCNAME { get; set; }
    public int? REQLOCID { get; set; }
    public int? LOCID { get; set; }
    public string? LOCCODE { get; set; }
    public string? LOCNAME { get; set; }
    public int SAMPLEID { get; set; }
    public string? SAMPLENUMBER { get; set; }
    public byte? SAMPSTATUS { get; set; }
    public int SAMPLABOID { get; set; }
}

public class PROBEREQUESTSWITHPENDINGMBREQ
{
    public int REQUESTID { get; set; }
    public string ACCESSNUMBER { get; set; } = string.Empty;
    public int REQCREATIONDATE { get; set; }
    public DateTime? REQDATE { get; set; }
    public DateTime? COLLECTIONDATE { get; set; }
    public int PATID { get; set; }
    public string? PATNUMBER { get; set; }
    public string? PATIENTNAME { get; set; }
    public string? PATIENTFIRSTNAME { get; set; }
    public int? SOURCELABOID { get; set; }
    public string? SOURCELABOCODE { get; set; }
    public int? REQDOCID { get; set; }
    public int? DOCID { get; set; }
    public string? DOCCODE { get; set; }
    public string? DOCNAME { get; set; }
    public int? REQLOCID { get; set; }
    public int? LOCID { get; set; }
    public string? LOCCODE { get; set; }
    public string? LOCNAME { get; set; }
    public int SUBREQUESTID { get; set; }
    public string SUBREQUESTNUMBER { get; set; } = string.Empty;
    public int? PRODLABOID { get; set; }
    public string? PRODLABOCODE { get; set; }
}

public class PROBEREQUESTSWITHTOBEPHONEDMB
{
    public int REQUESTID { get; set; }
    public string ACCESSNUMBER { get; set; } = string.Empty;
    public int REQCREATIONDATE { get; set; }
    public DateTime? REQDATE { get; set; }
    public DateTime? COLLECTIONDATE { get; set; }
    public int PATID { get; set; }
    public string? PATNUMBER { get; set; }
    public string? PATIENTNAME { get; set; }
    public string? PATIENTFIRSTNAME { get; set; }
    public int? SOURCELABOID { get; set; }
    public string? SOURCELABOCODE { get; set; }
    public int? REQDOCID { get; set; }
    public int? DOCID { get; set; }
    public string? DOCCODE { get; set; }
    public string? DOCNAME { get; set; }
    public int? REQLOCID { get; set; }
    public int? LOCID { get; set; }
    public string? LOCCODE { get; set; }
    public string? LOCNAME { get; set; }
    public int SUBREQUESTID { get; set; }
    public string SUBREQUESTNUMBER { get; set; } = string.Empty;
    public int? PRODLABOID { get; set; }
    public string? PRODLABOCODE { get; set; }
}

public class DICT_QA_DOCTYPES
{
    public int DOCTYPEID { get; set; }
    public int? APPROCYCLEID { get; set; }
    public string DOCTYPECODE { get; set; } = string.Empty;
    public int DOCTYPECREDATE { get; set; }
    public string SHORTTEXT { get; set; } = string.Empty;
    public string? FULLTEXT { get; set; }
    public string PREFIX { get; set; } = string.Empty;
    public int COUNTERID { get; set; }
    public string? SUFFIX { get; set; }
    public string? NAMEFILEEXTENSION { get; set; }
    public int? REVISIONPERIOD { get; set; }
    public string? TEMPLATEREFERENCE { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime? STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string? LOGUSERID { get; set; }
    public DateTime? LOGDATE { get; set; }
}

public class QA_DOCUMENT_STEPS
{
    public int STEPID { get; set; }
    public int DOCUMENTID { get; set; }
    public string? COMPLETEDBYID { get; set; }
    public string? ACTORID { get; set; }
    public string STEPNAME { get; set; } = string.Empty;
    public int LISTORDER { get; set; }
    public DateTime STEPCREDATE { get; set; }
    public DateTime? COMPLETEDDATE { get; set; }
    public string? LOGUSERID { get; set; }
    public DateTime? LOGDATE { get; set; }
}

public class QA_DOCUMENTS
{
    public int DOCUMENTID { get; set; }
    public int DOCTYPEID { get; set; }
    public int? DOCTEMPLATEID { get; set; }
    public int DOCSTATUS { get; set; }
    public string DOCREFERENCE { get; set; } = string.Empty;
    public int DOCREVISION { get; set; }
    public DateTime DOCCREDATE { get; set; }
    public DateTime? DOCOBJREVDATE { get; set; }
    public string DOCTITLE { get; set; } = string.Empty;
    public string? DOCEXTENSION { get; set; }
    public byte DOCISTEMPLATE { get; set; }
    public string? DOCCOMMENT { get; set; }
    public string? DOCMODIF { get; set; }
    public string? DOCNOTES { get; set; }
    public string? LOGUSERID { get; set; }
    public DateTime? LOGDATE { get; set; }
}

public class SP_REQUESTS
{
    public string SP_ACCESSNUMBER { get; set; } = string.Empty;
    public string? HOSTORDERNUMBER { get; set; }
    public int PATID { get; set; }
    public DateTime? REQDATE { get; set; }
    public string? ROOMNUMBER { get; set; }
    public byte? TRANSMISSIONSTATUS { get; set; }
    public string? SP_LOCCODE { get; set; }
    public string? SP_DOCCODE { get; set; }
    public byte? REQURGENT { get; set; }
    public DateTime? COLLECTIONDATE { get; set; }
    public string? SP_HOSPNUMBER { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public byte? COLLDATESTATUS { get; set; }
    public byte? STATUS { get; set; }
    public byte? BARRIERNURSE { get; set; }
    public byte? INFECTIONRISK { get; set; }
    public int? PATCLASSID { get; set; }
    public string? USERFIELD1 { get; set; }
    public string? USERFIELD2 { get; set; }
    public byte? CATEGORY { get; set; }
    public byte? TOPHONE { get; set; }
    public int? SOURCELABOID { get; set; }
    public byte? VALREQUESTED { get; set; }
    public byte? EXTERNALCOLLECTION { get; set; }
}

public class SP_TESTS
{
    public string SP_ACCESSNUMBER { get; set; } = string.Empty;
    public int SP_TESTORDER { get; set; }
    public byte? DEPTH { get; set; }
    public byte? TESTTYPE { get; set; }
    public byte? RESTYPE { get; set; }
    public string SP_TESTCODE { get; set; } = string.Empty;
    public int SP_TESTCREDATE { get; set; }
    public string DATA_BASE { get; set; } = string.Empty;
    public string? COLLCOND { get; set; }
    public string? SP_RESULT { get; set; }
    public byte? SP_TESTSTATUS { get; set; }
    public string? SP_STNCODE { get; set; }
    public string? ORDERFILLERNUMBER { get; set; }
    public string? ORDERPLACERNUMBER { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public int? MAPCODEID { get; set; }
    public int? SP_REDUNDANCYCHECKID { get; set; }
}

public class SP_TUBES
{
    public int SPTUBEID { get; set; }
    public string TUBENB { get; set; } = string.Empty;
    public string DATA_BASE { get; set; } = string.Empty;
    public string SP_ACCESSNUMBER { get; set; } = string.Empty;
    public int PATID { get; set; }
    public byte TUBESTATUS { get; set; }
    public int? CONTAINERNB { get; set; }
    public string? SAMPLETYPE { get; set; }
    public int? SAMPLETYPE_CREDATE { get; set; }
    public string TUBETYPE { get; set; } = string.Empty;
    public int TUBETYPE_CREDATE { get; set; }
    public int? FILLINGRATE { get; set; }
    public string? COLLECTOR { get; set; }
    public DateTime? COLLECTIONDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public int? COLLID { get; set; }
    public byte? COLLDATESTATUS { get; set; }
    public DateTime? LABRECEPTIONDATE { get; set; }
    public byte? ADDITIONALTUBE { get; set; }
    public string? PRIMARYSAMPLENUMBER { get; set; }
}

public class SP_TUBETESTS
{
    public string SP_ACCESSNUMBER { get; set; } = string.Empty;
    public int SP_TESTORDER { get; set; }
    public string TUBENB { get; set; } = string.Empty;
    public string DATA_BASE { get; set; } = string.Empty;
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class PATIENT
{
    public int PATID { get; set; }
    public string? PATNUMBER { get; set; }
    public string? REFHOSPNUMBER { get; set; }
    public string? BENNUMBER { get; set; }
    public string INTNUMBER { get; set; } = string.Empty;
    public int? PATCREATIONDATE { get; set; }
    public int? TITLEID { get; set; }
    public string? NAME { get; set; }
    public string? MAIDENNAME { get; set; }
    public string? FIRSTNAME { get; set; }
    public string? NAMESK { get; set; }
    public string? MAIDENNAMESK { get; set; }
    public string? FIRSTNAMESK { get; set; }
    public string? ADDRESS1 { get; set; }
    public string? ADDRESS2 { get; set; }
    public string? CITY { get; set; }
    public string? STATE { get; set; }
    public string? POSTALCODE { get; set; }
    public string? COUNTRY { get; set; }
    public DateTime? BIRTHDATE { get; set; }
    public byte? SEX { get; set; }
    public string? TELEPHON { get; set; }
    public string? TELEPHON2 { get; set; }
    public string? FAX { get; set; }
    public string? EMAIL { get; set; }
    public DateTime? INCOMMINGDATE { get; set; }
    public DateTime? OUTPUTDATE { get; set; }
    public string? ROOMNUMBER { get; set; }
    public string? REFDOCTOR { get; set; }
    public string? REFLOCATION { get; set; }
    public DateTime? LASTUPDTESTDATE { get; set; }
    public DateTime? LASTREVIEWDATE { get; set; }
    public int? SAFETYMEASURES { get; set; }
    public byte? SECRETRESULT { get; set; }
    public byte? VIP { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public short? PRECAUTION { get; set; }
    public int? DOCID { get; set; }
    public int? PAYERPATID { get; set; }
}

public class DICT_TESTS
{
    public int TESTID { get; set; }
    public int? CHAPID { get; set; }
    public string TESTCODE { get; set; } = string.Empty;
    public int TESTCREDATE { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public byte? TESTTYPE { get; set; }
    public short? TESTRANK { get; set; }
    public string? UNITS { get; set; }
    public byte? RESTYPE { get; set; }
    public byte? RESPRECISION { get; set; }
    public string? VALUPPLIMIT { get; set; }
    public string? VALLOWLIMIT { get; set; }
    public byte? DUPLICATERESULT { get; set; }
    public string? FAMILY { get; set; }
    public string? HOSTCODE { get; set; }
    public string? HOSTTEXT { get; set; }
    public byte? PRINTABLEONSTAT { get; set; }
    public string? STATVALUE { get; set; }
    public string? KEYLETTERCODE { get; set; }
    public string? NBKEYLETTER { get; set; }
    public string? ICRCODE { get; set; }
    public byte? CUMPRINTOUT { get; set; }
    public byte? SECRETTEST { get; set; }
    public byte? REQUESTABLE { get; set; }
    public short? REDUNDANCYDURATION { get; set; }
    public byte? REDUNDANCYUNIT { get; set; }
    public byte? TABLEFORMAT { get; set; }
    public short? VOLUME { get; set; }
    public byte? CUMVOLUME { get; set; }
    public byte? NOTPRINTABLE { get; set; }
    public string? TESTCLASS { get; set; }
    public string? COMPOSITIONCLASS { get; set; }
    public string? CODEDTEXTCLASS { get; set; }
    public byte? DISPLAY { get; set; }
    public short? PERFORMANCEDURATION { get; set; }
    public byte? PERFORMANCEUNIT { get; set; }
    public byte? DAYMETHODISPERF { get; set; }
    public byte? MICROBIOTESTTYPE { get; set; }
    public string? CONSUMABLE { get; set; }
    public string? RESDEFAULT { get; set; }
    public byte? RESTYPEDEFAULT { get; set; }
    public short? COMBPRINT { get; set; }
    public short? VALIDATIONMANDATORY { get; set; }
    public byte? SEX { get; set; }
    public byte? PRECISIONRELATED { get; set; }
    public string? UNITS2 { get; set; }
    public byte? RESPRECISION2 { get; set; }
    public short? OPERAND { get; set; }
    public string? SOFTCONVERSION { get; set; }
    public byte? PRECISION2RELATED { get; set; }
    public string? INTERNATIONALCODE { get; set; }
    public byte? MULTIPLERANGES { get; set; }
    public string? LISTESTCODE { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public string? ACTCODE { get; set; }
    public byte? MANDATORY { get; set; }
    public byte? NONREVIEWRESAVAILABLE { get; set; }
}

public class DICT_TEST_SAMPLES
{
    public int TESTID { get; set; }
    public int SAMPTYPEID { get; set; }
    public byte PRIORITYLEVEL { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_SAMPLES_TYPES
{
    public int SAMPTYPEID { get; set; }
    public string SAMPCODE { get; set; } = string.Empty;
    public int SAMPCREDATE { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? HOSTCODE { get; set; }
    public string? HOSTTEXT { get; set; }
    public int? NUMCODE { get; set; }
    public string? FULLTEXT { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public int? TUBETYPEID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public byte? TOBEDECANTED { get; set; }
}

public class DICT_COLLECTORS
{
    public int COLLID { get; set; }
    public byte? COLLTYPE { get; set; }
    public string COLLCODE { get; set; } = string.Empty;
    public int COLLCREDATE { get; set; }
    public string? COLLNAME { get; set; }
    public int? TITLEID { get; set; }
    public int? SITEID { get; set; }
    public string? ADDRESS1 { get; set; }
    public string? ADDRESS2 { get; set; }
    public string? CITY { get; set; }
    public string? STATE { get; set; }
    public string? POSTALCODE { get; set; }
    public string? COUNTRY { get; set; }
    public string? TELEPHON { get; set; }
    public string? TELEPHON2 { get; set; }
    public string? FAX { get; set; }
    public string? EMAIL { get; set; }
    public string? INFORMATION { get; set; }
    public string? NATIONALCODE { get; set; }
    public string? HOSTCODE { get; set; }
    public string? HOSTTEXT { get; set; }
    public byte? TARIFFAREA { get; set; }
    public byte? SPECIALITY { get; set; }
    public byte? COLLONFSS { get; set; }
    public string? LISCOLLCODE { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_TEXTS
{
    public int TEXTID { get; set; }
    public string TEXTCODE { get; set; } = string.Empty;
    public int TEXTCREDATE { get; set; }
    public byte TEXTTYPE { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? HOSTCODE { get; set; }
    public string? HOSTTEXT { get; set; }
    public int? NUMCODE { get; set; }
    public string? TEXTCLASS { get; set; }
    public byte? IGNORERES { get; set; }
    public string? BARCODE { get; set; }
    public string? FAMILY { get; set; }
    public byte? MICROBIOTEXTTYPE { get; set; }
    public byte? SEX { get; set; }
    public string? FULLTEXT { get; set; }
    public string? LISTEXTCODE { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_TESTS_V3
{
    public int TESTID { get; set; }
    public string TESTCODE { get; set; } = string.Empty;
    public int TESTCREDATE { get; set; }
}

public class DICT_TUBES_TYPES_V3
{
    public int TEXTID { get; set; }
    public string TEXTCODE { get; set; } = string.Empty;
    public int TEXTCREDATE { get; set; }
}

public class SP_REQUEST_DOCTORS
{
    public string SP_ACCESSNUMBER { get; set; } = string.Empty;
    public short DOCRANK { get; set; }
    public string DOCCODE { get; set; } = string.Empty;
    public short? RECEIVEDBYCNX { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SP_REQUESTS_OCOM
{
    public string SP_ACCESSNUMBER { get; set; } = string.Empty;
    public string? COMMENTTEXT { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DOCTORS
{
    public int REQDOCID { get; set; }
    public int REQUESTID { get; set; }
    public int DOCID { get; set; }
    public byte? PRINTOUTNUMBER { get; set; }
    public DateTime? DOCREPORTDATE { get; set; }
    public byte? PRESCRIBER { get; set; }
    public byte? SENDREPORT { get; set; }
    public short? PATIENTREPORT { get; set; }
    public int? DISCIPLINE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class HOSPITALIZATIONS
{
    public int HOSPITID { get; set; }
    public int PATID { get; set; }
    public string HOSPITNUMBER { get; set; } = string.Empty;
    public int HOSPITCREDATE { get; set; }
    public DateTime? INCOMMINGDATE { get; set; }
    public DateTime? OUTPUTDATE { get; set; }
    public int? PATCLASSID { get; set; }
    public int? FINCLASSID { get; set; }
    public DateTime? FINCLASSDATE { get; set; }
    public int? LOCID { get; set; }
    public string? ROOMNUMBER { get; set; }
    public int? REFDOCID { get; set; }
    public int? ADMDOCID { get; set; }
    public int? ATTENDOCID { get; set; }
    public int? CONSULTDOCID { get; set; }
    public int? SERVICEID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public string? EXTERNALHOSNUM { get; set; }
    public string? BEDNUMBER { get; set; }
}

public class LOCATIONS
{
    public int REQLOCID { get; set; }
    public int REQUESTID { get; set; }
    public int LOCID { get; set; }
    public byte? PRINTOUTNUMBER { get; set; } // TODO
    public DateTime? LOCREPORTDATE { get; set; }
    public byte? SENDREPORT { get; set; }
    public short? PATIENTREPORT { get; set; }
    public int? DISCIPLINE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class REQUESTS
{
    public int REQUESTID { get; set; }
    public string ACCESSNUMBER { get; set; } = string.Empty;
    public int REQCREATIONDATE { get; set; }
    public int PATID { get; set; }
    public int? HOSPITID { get; set; }
    public string? EXTERNALORDERNUMBER { get; set; }
    public byte? CATEGORY { get; set; }
    public string? REDACCNUM { get; set; }
    public byte? REQSTATUS { get; set; }
    public DateTime? STATUSDATE { get; set; }
    public DateTime? REQDATE { get; set; }
    public DateTime? COLLECTIONDATE { get; set; }
    public byte URGENT { get; set; }
    public int? LABOID { get; set; }
    public string? ROOMNUMBER { get; set; }
    public DateTime? LASTUPDTESTDATE { get; set; }
    public byte? REQTOVALID { get; set; }
    public string? REQURL { get; set; }
    public byte? TOPHONE { get; set; }
    public DateTime? LMP { get; set; }
    public byte? NBCHILDS { get; set; }
    public DateTime? AUTODATE { get; set; }
    public string? NECROSCOPY { get; set; }
    public string? ENCLOSED { get; set; }
    public DateTime? RECEIVEDDATE { get; set; }
    public byte? RECBYCNX { get; set; }
    public string? LISUSER { get; set; }
    public DateTime? LISDATE { get; set; }
    public string? LOGSESSION { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public DateTime? STANDORDERVALIDITYDATE { get; set; }
    public byte? EXPIREDSTANDORDER { get; set; }
    public int? STANDORDERNBOCC { get; set; }
    public string? USERFIELD1 { get; set; }
    public string? USERFIELD2 { get; set; }
    public byte? CREATEDONTDR { get; set; }
    public int? SOURCESITEID { get; set; }
    public byte? PATHOGEN { get; set; }
    public byte? EXTERNALCOLLECTION { get; set; }
    public byte? ALLPRINTED { get; set; }
    public byte? VALREQUESTED { get; set; }
}

public class DICT_RACKS
{
    public int DICTRACKID { get; set; }
    public int STORAGEID { get; set; }
    public byte? MOVEABLE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public string? RACKNBROW { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string RACKNBCOL { get; set; } = string.Empty;
    public string RACKCODE { get; set; } = string.Empty;
    public int RACKCREDATE { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public byte RACKSTATUS { get; set; }
}

public class DICT_STORAGE_LOCATIONS
{
    public int STORAGEID { get; set; }
    public string STORAGENAME { get; set; } = string.Empty;
    public int? STORAGELASTRACK { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public byte STORAGETYPE { get; set; }
}

public class RACK_POSITIONS
{
    public int RACKID { get; set; }
    public int COLUMNPOSITION { get; set; }
    public int? ROWPOSITION { get; set; }
    public int SAMPLEID { get; set; }
    public DateTime RACKDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SAMPLE_TRACKING
{
    public int SAMPLEID { get; set; }
    public int? SITEID { get; set; }
    public int? LABOID { get; set; }
    public int? DEPARTMENTID { get; set; }
    public int? TECHNICALGROUPID { get; set; }
    public int? STNID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SAMPLES
{
    public int SAMPLEID { get; set; }
    public int REQUESTID { get; set; }
    public string FULLSAMPLENUM { get; set; } = string.Empty;
    public string? SAMPLENUMBER { get; set; }
    public byte? TUBENUMBER { get; set; }
    public int? SAMPTYPEID { get; set; }
    public byte? SAMPSTATUS { get; set; }
    public byte? URGENT { get; set; }
    public string? TXTCOLLCOND { get; set; }
    public int? COLLID { get; set; }
    public DateTime? COLLECTIONDATE { get; set; }
    public int? STNSAMPLENUMBER { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public int? TUBEINDEX { get; set; }
    public byte? DECANT { get; set; }
    public DateTime? LABRECEPTIONDATE { get; set; }
    public byte? CREATEDONTDR { get; set; }
    public int? PRIMSAMPLEID { get; set; }
    public string? LABRECEPTIONBY { get; set; }
    public byte? RANK { get; set; }
}

public class DICT_TRANSPORTATION_STORAGE
{
    public int STORAGEID { get; set; }
    public int MAXTRANSITTIME { get; set; }
    public byte MAXTRANSITTIMEUNITS { get; set; }
    public int? SOURCELABOID { get; set; }
    public int? TARGETLABOID { get; set; }
    public int? TARGETSITEID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public int? SOURCESITEID { get; set; }
}

public class DICT_LABORATORIES
{
    public int LABOID { get; set; }
    public string LABOCODE { get; set; } = string.Empty;
    public int LABOCREDATE { get; set; }
    public string? LABOTEXT { get; set; }
    public string? SHORTTEXT { get; set; }
    public byte? LISACCOUNTINGMODE { get; set; }
    public string? ADDRESS1 { get; set; }
    public string? ADDRESS2 { get; set; }
    public string? CITY { get; set; }
    public string? STATE { get; set; }
    public string? POSTALCODE { get; set; }
    public string? COUNTRY { get; set; }
    public string? TELEPHON { get; set; }
    public string? TELEPHON2 { get; set; }
    public string? FAX { get; set; }
    public string? EMAIL { get; set; }
    public string? NATIONALCODE { get; set; }
    public int? BILREMINDFLEVEL { get; set; }
    public int? BILREMINDSLEVEL { get; set; }
    public int? BILREMINDTLEVEL { get; set; }
    public int? BILREMINDCOVERYDEP { get; set; }
    public int? BILFREMINDERFEES { get; set; }
    public int? BILSREMINDERFEES { get; set; }
    public int? BILTREMINDERFEES { get; set; }
    public int? BILFREMINDMINAMOUNT { get; set; }
    public int? BILSREMINDMINAMOUNT { get; set; }
    public int? BILTREMINDMINAMOUNT { get; set; }
    public int? BILNUMBERCOUNTER { get; set; }
    public string? BILPREFIXBILLING { get; set; }
    public byte? BILTRANSMODE { get; set; }
    public short? PATIENTREPORT { get; set; }
    public string ALTERNATECODE { get; set; } = string.Empty;
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public string? LABOSERVICEID { get; set; }
    public string? AUTHORIZERID { get; set; }
}

public class DICT_SITES
{
    public int SITEID { get; set; }
    public string SITECODE { get; set; } = string.Empty;
    public int SITECREDATE { get; set; }
    public string SHORTTEXT { get; set; } = string.Empty;
    public string? FULLTEXT { get; set; }
    public string? ADDRESS1 { get; set; }
    public string? ADDRESS2 { get; set; }
    public string? POSTALCODE { get; set; }
    public string? CITY { get; set; }
    public string? STATE { get; set; }
    public string? COUNTRY { get; set; }
    public string? TELEPHON { get; set; }
    public string? FAX { get; set; }
    public string? EMAIL { get; set; }
    public string ALTERNATECODE { get; set; } = string.Empty;
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public string? PREFIX { get; set; }
}

public class DICT_DOCTORS
{
    public int DOCID { get; set; }
    public string DOCCODE { get; set; } = string.Empty;
    public int DOCCREDATE { get; set; }
    public string? DOCNAME { get; set; }
    public int? TITLEID { get; set; }
    public string? ADDRESS1 { get; set; }
    public string? ADDRESS2 { get; set; }
    public string? CITY { get; set; }
    public string? STATE { get; set; }
    public string? POSTALCODE { get; set; }
    public string? COUNTRY { get; set; }
    public string? TELEPHON { get; set; }
    public string? TELEPHON2 { get; set; }
    public string? FAX { get; set; }
    public string? EMAIL { get; set; }
    public string? HOSTCODE { get; set; }
    public string? HOSTTEXT { get; set; }
    public string? INFORMATION { get; set; }
    public string? GROUP1 { get; set; }
    public string? GROUP2 { get; set; }
    public string? GROUP3 { get; set; }
    public string? GROUP4 { get; set; }
    public string? NATIONALCODE { get; set; }
    public byte? TOPHONE { get; set; }
    public string? PRESCRIBDISC { get; set; }
    public byte? SENDREPORT { get; set; }
    public byte? SENDFAX { get; set; }
    public short? PATIENTREPORT { get; set; }
    public int? TESTID { get; set; }
    public int? PRICEGROUPID { get; set; }
    public string? DEFAULTLOCCODE { get; set; }
    public string? LISDOCCODE { get; set; }
    public byte? SPECIALTY { get; set; }
    public string? LISTELEM1 { get; set; }
    public string? LISTELEM2 { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_LOCATIONS
{
    public int LOCID { get; set; }
    public string LOCCODE { get; set; } = string.Empty;
    public int LOCCREDATE { get; set; }
    public string? LOCNAME { get; set; }
    public int? TITLEID { get; set; }
    public string? ADDRESS1 { get; set; }
    public string? ADDRESS2 { get; set; }
    public string? CITY { get; set; }
    public string? STATE { get; set; }
    public string? POSTALCODE { get; set; }
    public string? COUNTRY { get; set; }
    public string? TELEPHON { get; set; }
    public string? TELEPHON2 { get; set; }
    public string? FAX { get; set; }
    public string? EMAIL { get; set; }
    public string? HOSTCODE { get; set; }
    public string? HOSTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public string? INFORMATION { get; set; }
    public byte? FIRSTDISPLAYISCUM { get; set; }
    public byte? MODIFPRESCRIPTIONNB { get; set; }
    public short? REDUNDANCYDURATION { get; set; }
    public byte? REDUNDANCYUNIT { get; set; }
    public byte? COLLECTORMANDATORY { get; set; }
    public short? ENQUIRYDURATION { get; set; }
    public short? RETENTIONDURATION { get; set; }
    public byte? COLLECTIONSPERFORMED { get; set; }
    public string? GROUP1 { get; set; }
    public string? GROUP2 { get; set; }
    public string? GROUP3 { get; set; }
    public string? GROUP4 { get; set; }
    public string? NATIONALCODE { get; set; }
    public byte? TOPHONE { get; set; }
    public byte? CATEGORY { get; set; }
    public byte? SENDREPORT { get; set; }
    public byte? SENDFAX { get; set; }
    public short? SENDRECALL { get; set; }
    public short? PATIENTREPORT { get; set; }
    public int? TESTID { get; set; }
    public int? PRICEGROUPID { get; set; }
    public string? DEFDISCCODE { get; set; }
    public int? AUTONUMBERID { get; set; }
    public int? ORGANISATID { get; set; }
    public string? LISLOCCODE { get; set; }
    public short? IMMEDIATELABLAYOUT { get; set; }
    public string? LISTELEM1 { get; set; }
    public string? LISTELEM2 { get; set; }
    public int? SITEID { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public byte? ISVOLUMEUSED { get; set; }
}

public class DICT_WORKSTATIONS
{
    public int STNID { get; set; }
    public string STNCODE { get; set; } = string.Empty;
    public int STNCREDATE { get; set; }
    public byte? STNTYPE { get; set; }
    public string? STNNAME { get; set; }
    public short? STNTECSECTION { get; set; }
    public byte? STNNUMSIZE { get; set; }
    public byte? STNNUMTYPE { get; set; }
    public byte? STNACCNUMSIZE { get; set; }
    public byte? STNIDX { get; set; }
    public byte? STNIDXSIZE { get; set; }
    public byte? STNNBLABEL { get; set; }
    public int? STORAGEID { get; set; }
    public byte? REPLICSAMPLESMODE { get; set; }
    public byte? TREATMODE { get; set; }
    public string ALTERNATECODE { get; set; } = string.Empty;
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public byte? STNSTATUS { get; set; }
    public byte? SAMPLERECEPTYPE { get; set; }
    public short? CHRONOIDCOUNTER { get; set; }
    public byte? CHRONOIDUSEYEAR { get; set; }
    public string? CHRONOIDPREFIX { get; set; }
    public byte? CHRONOIDCOUNTERLENGTH { get; set; }
}

public class DICT_CHAPTERS
{
    public int CHAPID { get; set; }
    public string CHAPCODE { get; set; } = string.Empty;
    public int CHAPCREDATE { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? HOSTCODE { get; set; }
    public string? HOSTTEXT { get; set; }
    public int? NUMCODE { get; set; }
    public int? DISCNUMCODE { get; set; }
    public string? FULLTEXT { get; set; }
    public string? LISCHAPCODE { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class TEST
{
    public int REQTESTID { get; set; }
    public int? CHAPID { get; set; }
    public int TESTID { get; set; }
    public int? STNID { get; set; }
    public int REQUESTID { get; set; }
    public int LISTESTID { get; set; }
    public int? TESTORDER { get; set; }
    public byte? DEPTH { get; set; }
    public string? TXTCOLLCOND { get; set; }
    public byte STNPRIORITYLEVEL { get; set; }
    public byte? NOTPRINTABLE { get; set; }
    public byte? VALIDATIONCAUSE { get; set; }
    public string? VALIDATIONINITIALS { get; set; }
    public byte? VALIDATIONSTATUS { get; set; }
    public byte? RESTYPE { get; set; }
    public string? RESVALUE { get; set; }
    public byte? RESSTATUS { get; set; }
    public DateTime? RESUPDDATE { get; set; }
    public DateTime? LASTUPDTESTDATE { get; set; }
    public int? CODEDRESULTID { get; set; }
    public string? MINIMUM { get; set; }
    public string? MAXIMUM { get; set; }
    public byte? SECRETTEST { get; set; }
    public byte? UPDSTATUS { get; set; }
    public int? LABOID { get; set; }
    public byte? BINDATALINK { get; set; }
    public string? ORDERPLACERNUMBER { get; set; }
    public string? ORDERFILLERNUMBER { get; set; }
    public string? TESTURL { get; set; }
    public int? SAMPLEID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public int? INSTPERI { get; set; }
    public int? INSTNUM { get; set; }
    public string? TECHNICALINITIALS { get; set; }
    public byte? CREATEDONTDR { get; set; }
    public string? INST_IDENTIFIER { get; set; }
    public byte? RERUN { get; set; }
    public DateTime? VALIDATIONDATE { get; set; }
    public DateTime? FIRSTVALIDATIONDATE { get; set; }
}

public class TESTS_COMMENT
{
    public int REQTESTID { get; set; }
    public byte TESTCOMSUBJECT { get; set; }
    public byte COMMENTTYPE { get; set; }
    public string? COMMENTTEXT { get; set; }
    public int? COMMENTCODEDID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class WS_TEST_COMMENT
{
    public int WSTESTID { get; set; }
    public byte WSTESTCOMSUBJECT { get; set; }
    public byte COMMENTTYPE { get; set; }
    public string? COMMENTTEXT { get; set; }
    public int? COMMENTCODEDID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public int? BUILD208 { get; set; }
}

public class SAMPLE_AVAILABILITY
{
    public int RECEIVEID { get; set; }
    public int SAMPLEID { get; set; }
    public int? LABOID { get; set; }
    public int? STNID { get; set; }
    public DateTime? RECEIVEDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SAMPLE_COMMENTS
{
    public int SAMPLEID { get; set; }
    public byte SAMPCOMSUBJECT { get; set; }
    public byte COMMENTTYPE { get; set; }
    public string? COMMENTTEXT { get; set; }
    public int? COMMENTCODEDID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_TEST_PERF_ON
{
    public int PERFONID { get; set; }
    public int STNID { get; set; }
    public int TESTID { get; set; }
    public int? METHODID { get; set; }
    public byte URGLEVEL { get; set; }
    public int? SITEID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DEPARTMENT_LABORATORY
{
    public int DEPARTMENTID { get; set; }
    public int LABOID { get; set; }
}

public class LABORATORY_SITE
{
    public int LABOID { get; set; }
    public int SITEID { get; set; }
}

public class TECHGROUP_DEPARTMENT
{
    public int TECHNICALGROUPID { get; set; }
    public int DEPARTMENTID { get; set; }
}

public class WORKSTATION_TECHGROUP
{
    public int STNID { get; set; }
    public int TECHNICALGROUPID { get; set; }
}

public class DICT_DEPARTMENTS
{
    public int DEPARTMENTID { get; set; }
    public string DEPARTMENTCODE { get; set; } = string.Empty;
    public int DEPARTMENTCREDATE { get; set; }
    public string SHORTTEXT { get; set; } = string.Empty;
    public string? FULLTEXT { get; set; }
    public string ALTERNATECODE { get; set; } = string.Empty;
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public string? DEPARTMENTSERVICEID { get; set; }
    public int? PRINTERNUMBER { get; set; }
    public string? AUTHORIZERID { get; set; }
}

public class DICT_TECHNICAL_GROUPS
{
    public int TECHNICALGROUPID { get; set; }
    public string TECHNICALGROUPCODE { get; set; } = string.Empty;
    public int TECHNICALGROUPCREDATE { get; set; }
    public string SHORTTEXT { get; set; } = string.Empty;
    public string? FULLTEXT { get; set; }
    public string ALTERNATECODE { get; set; } = string.Empty;
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public string? TECHNICALGROUPSERVICEID { get; set; }
}

public class DICT_WORKSTATIONS_V3
{
    public int STNID { get; set; }
    public string STNCODE { get; set; } = string.Empty;
}

public class DICT_LOCATIONS_V3
{
    public int LOCID { get; set; }
    public string LOCCODE { get; set; } = string.Empty;
}

public class ROLE_PRIV
{
    public string ROLENAME { get; set; } = string.Empty;
    public short PRIVID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class ROLE
{
    public string ROLENAME { get; set; } = string.Empty;
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class USER_ROLE
{
    public string USERID { get; set; } = string.Empty;
    public int CONFIGID { get; set; }
    public string ROLENAME { get; set; } = string.Empty;
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class USER
{
    public string USERID { get; set; } = string.Empty;
    public string? USERNAME { get; set; }
    public byte? USERLANGUAGE { get; set; }
    public int? USERTIMEOUT { get; set; }
    public byte? DEFAULTACCESS { get; set; }
    public int? DOCID { get; set; }
    public int? USERLEVEL { get; set; }
    public string? USERINITIALS { get; set; }
    public string? NATIONALCODE { get; set; }
    public DateTime? LASTCARDLOGIN { get; set; }
    public int? LABOID { get; set; }
    public byte? DEFAULTUNIT { get; set; }
    public string? QUALIFICATION { get; set; }
    public string? EMAIL { get; set; }
    public string? TELEPHON { get; set; }
    public byte? LOCKEDACCOUNT { get; set; }
    public DateTime? USERLOGIN { get; set; }
    public DateTime? USERLOGOUT { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public byte? RESERVEDUSER { get; set; }
    public string? SIGNID { get; set; }
}

public class PARAM_VALUES
{
    public string PARAMID { get; set; } = string.Empty;
    public int CONFIGID { get; set; }
    public string? PARAMVALUE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class CONFIG
{
    public int CONFIGID { get; set; }
    public byte CONFIGTYPE { get; set; }
    public string CONFIGNAME { get; set; } = string.Empty;
    public int? CONFIGORDER { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SAMPLE_TRANSPORT
{
    public int SAMPLETRANSPORTID { get; set; }
    public int SAMPLEID { get; set; }
    public int? SOURCELABOID { get; set; }
    public int? TARGETLABOID { get; set; }
    public DateTime? INRACKDATE { get; set; }
    public DateTime? PICKUPDATE { get; set; }
    public DateTime? RECEPTIONDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public int? TARGETSITEID { get; set; }
    public string? INRACKBY { get; set; }
    public string? PICKUPBY { get; set; }
    public string? RECEPTIONBY { get; set; }
}

public class DICT_CATEGORIES
{
    public int CATID { get; set; }
    public int? LABOID { get; set; }
    public string CATCODE { get; set; } = string.Empty;
    public DateTime CATCREDATE { get; set; }
    public string SHORTTEXT { get; set; } = string.Empty;
    public int NUMCODE { get; set; }
    public int? BUTARID { get; set; }
    public int? CATALOGID { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_PAT_CLASS
{
    public int PATCLASSID { get; set; }
    public string PATCLASSCODE { get; set; } = string.Empty;
    public int PATCLASSCREDATE { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public int? CATID { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public DateTime LOGDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
}

public class REQUESTS_OCOM
{
    public int REQUESTID { get; set; }
    public byte REQCOMSUBJECT { get; set; }
    public byte COMMENTTYPE { get; set; }
    public string? COMMENTTEXT { get; set; }
    public int? COMMENTCODEDID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_TEST_COMP
{
    public int TESTID { get; set; }
    public int COMBTESTID { get; set; }
    public byte COMBTESTORDER { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class PATIENTS_PCOM
{
    public int PATID { get; set; }
    public byte PATCOMSUBJECT { get; set; }
    public byte COMMENTTYPE { get; set; }
    public string? COMMENTTEXT { get; set; }
    public int? COMMENTCODEDID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class STORAGE_LOCATION_POST
{
    public int STORAGEID { get; set; }
    public int LABOID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class STORAGE_LOCATION_PRE
{
    public int STORAGEID { get; set; }
    public int LABOID { get; set; }
    public DateTime LOGDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
}

public class LOCATION_DOCTORS
{
    public int LOCDOCID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class USERS_HC
{
    public string USERHCID { get; set; } = string.Empty;
    public int? SPECIALITYID { get; set; }
    public string USERIDTDR { get; set; } = string.Empty;
    public int? USERSLIDETOREFER { get; set; }
    public int? USERTOTNORMSLIDES { get; set; }
    public int? USERTOTREFERSLIDES { get; set; }
    public byte? USERDISC { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_BINARY_DATA
{
    public int DICBINARYID { get; set; }
    public int OBJECTLINK { get; set; }
    public int OBJECTTYPE { get; set; }
    public short DICBINARYTYPE { get; set; }
    public DateTime BINARYDATE { get; set; }
    public string? BINARYMIMETYPE { get; set; }
    public int? BINARYSIZE { get; set; }
    public string? BINARYVALUE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public byte[]? BINARYOBJECT { get; set; }
}

public class DICT_TESTS_PERF_ON_ADD_DATA
{
    public string SITECODE { get; set; } = string.Empty;
    public string TESTCODE { get; set; } = string.Empty;
    public byte URGENT { get; set; }
    public string SAMPLECODE { get; set; } = string.Empty;
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_MEDICAL_DISCIPLINES
{
    public int MEDICALDISCID { get; set; }
    public string MDCODE { get; set; } = string.Empty;
    public int MDCREDATE { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class ACTION_MARKS
{
    public int ACTIONMARKID { get; set; }
    public int? ACTIONMARKCLASS { get; set; }
    public DateTime ACTIONMARKDATE { get; set; }
    public string ACTIONMARKUSERID { get; set; } = string.Empty;
    public int? OBJECTLINK { get; set; }
    public string? ACTIONMARKDATA1 { get; set; }
    public string? ACTIONMARKDATA2 { get; set; }
    public string? ACTIONMARKDATA3 { get; set; }
    public string? ACTIONMARKDATA4 { get; set; }
    public string? ACTIONMARKDATA5 { get; set; }
    public DateTime LOGDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
}

public class CollectionOrderLabelEvent
{
}

public class OnLinePaymentEvent
{
}

public class SubRequestMBEvent
{
}

public class ALTERNATE_IDENTIFIERS
{
    public int ALTNIDENTIFIERID { get; set; }
    public string IDENTIFIERNUMBER { get; set; } = string.Empty;
    public string? ASSIGNINGAUTHORITY { get; set; }
    public string? IDENTIFIERTYPECODE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_IDENTIFIERNAME
{
    public int IDENTIFIERNAMEID { get; set; }
    public string IDENTIFIERNAMECODE { get; set; } = string.Empty;
    public int? IDENTIFIERNAMECREDATE { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_DEVICES
{
    public int DEVICEID { get; set; }
    public string DEVICECODE { get; set; } = string.Empty;
    public int DEVICECREDATE { get; set; }
    public string? DEVICENAME { get; set; }
    public int? DEVICETYPE { get; set; }
    public byte? DEVICESTATUS { get; set; }
    public string? SERVICENAME { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public string? PROTOCOLDLL { get; set; }
    public string? FORMATDLL { get; set; }
    public string? TRANSPORTDLL { get; set; }
    public string? APPLICATIONDLL { get; set; }
    public string? DEVICEGROUP { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_SPECIALITIES
{
    public int SPECIALITYID { get; set; }
    public int? DICTSPECID { get; set; }
    public int? LABOID { get; set; }
    public string SPECIALITYCODE { get; set; } = string.Empty;
    public int SPECIALITYCREDATE { get; set; }
    public short? SPECIALITYTYPE { get; set; }
    public string? SHORTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public string? DEFSPECCODE { get; set; }
    public int? AUTONUMBERID { get; set; }
    public string? DEFCODE { get; set; }
    public short? DEFCODETYPE { get; set; }
    public string? SPECIMENLABELFILE { get; set; }
    public short? NBLABELSPERSPECIMEN { get; set; }
    public short? ONELABELFORREQUEST { get; set; }
    public string? REQNBLONGPREFIX { get; set; }
    public string? REQNBSEPARATOR { get; set; }
    public byte? REQNBCOUNTERLENGTH { get; set; }
    public int? DISCIPLINE { get; set; }
    public string? CNXLMXCOMBTEST { get; set; }
    public string? CNXLMXSPECNUM { get; set; }
    public short AUTOREPORT { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public byte? BRCSENDTYPE { get; set; }
    public string? BRCXMLDIR { get; set; }
    public string? SPECNBSEPARATOR { get; set; }
    public byte? SPECNBCOUNTERLENGTH { get; set; }
    public string? BLOCKNBSEPARATOR { get; set; }
    public byte? BLOCKNBCOUNTERLENGTH { get; set; }
    public short AUTOTECHFORM { get; set; }
    public short AUTOLABEL { get; set; }
    public short TECHFORMATRECEP { get; set; }
    public short LABELSATRECEP { get; set; }
}

public class JOB_PARAMETERS
{
    public int JOBPARAMRID { get; set; }
    public int JOBPARAMTYPE { get; set; }
    public string? JOBPARAMNAME { get; set; }
    public string? JOBPARAMVALUE { get; set; }
    public string? JOBPARAMMIME { get; set; }
    public int? JOBPARAMSIZE { get; set; }
    public byte[]? JOBPARAMBLOB { get; set; }
    public string? CONTENTDESCR { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class JOBS
{
    public int JOBID { get; set; }
    public byte? JOBPRIORITY { get; set; }
    public byte? JOBSTATUS { get; set; }
    public int JOBTYPE { get; set; }
    public int? JOBRANK { get; set; }
    public string JOBNAME { get; set; } = string.Empty;
    public DateTime JOBDATE { get; set; }
    public int? JOBSIZE { get; set; }
    public byte? NBCOPIES { get; set; }
    public short? RESEND { get; set; }
    public string? COMMENTTEXT { get; set; }
    public short? JOBERRORCLASS { get; set; }
    public string? JOBERRORMESSAGE { get; set; }
    public string? JOBERRORFSEDATA { get; set; }
    public DateTime? SUBMITTEDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class REVIEW
{
    public int REQUESTID { get; set; }
    public int PATID { get; set; }
    public DateTime REVIEWDATE { get; set; }
    public string LOCCODE { get; set; } = string.Empty;
    public string USERID { get; set; } = string.Empty;
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class USER_PASSWORDS
{
    public int PASSWORDID { get; set; }
    public string? PASSWORD { get; set; }
    public byte? ENCRYPTEDPWD { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class ATR_COPIES
{
    public string ATR_ACCESSNUMBER { get; set; } = string.Empty;
    public int ATR_CREATIONDATE { get; set; }
    public byte STEPTYPE { get; set; }
    public DateTime STEPDATE { get; set; }
    public string ATR_DOCCOPY { get; set; } = string.Empty;
}

public class ACTS
{
    public int INVACTID { get; set; }
    public int? BUCOSTID { get; set; }
    public int? BUCOSTIDAGREEMENT { get; set; }
    public int? LISINVACTID { get; set; }
    public byte? ACTNATURE { get; set; }
    public string? ACTREF { get; set; }
    public int? NBACT { get; set; }
    public string? BILLUREF { get; set; }
    public int? NBBILLU { get; set; }
    public int? EXTRA { get; set; }
    public int? SCEANCE { get; set; }
    public byte? BILLRATE { get; set; }
    public byte? NONLISTEDACT { get; set; }
    public byte? REFUND100 { get; set; }
    public byte? DISCIPLINENB { get; set; }
    public byte? IMPEGNUM { get; set; }
    public int? AMOUNTDUE { get; set; }
    public byte? ACTSTATUS { get; set; }
    public byte? ACTCANCELED { get; set; }
    public string? CHARGEDELCOMMENT { get; set; }
    public DateTime? CHARGEDELDATE { get; set; }
    public string? CHARGEDELUSERID { get; set; }
    public int? EXONERATION { get; set; }
    public byte? USERCHOICE { get; set; }
    public DateTime? ACTDATE { get; set; }
    public int? KEYLETTERPRICE { get; set; }
    public int? ACTIVITY { get; set; }
    public string? MODIFIER { get; set; }
    public int? ASSOCIATION { get; set; }
    public int? TREATMENT_PHASE { get; set; }
    public int? EXCEPTIONALREIMBURSEMENT { get; set; }
    public string? DOCUMENTARYEXTENSION { get; set; }
    public string? SUPPLEMENTARYCHARGE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class CUSTOMER_PROFILES
{
    public int CUSTOMPROFILID { get; set; }
    public string INTNUMBER { get; set; } = string.Empty;
    public byte REGTYPE { get; set; }
    public string? REGNUMBER { get; set; }
    public DateTime? RIGHTSENDDATE { get; set; }
    public byte? VALIDRIGHTS { get; set; }
    public string? INSKEYNUMBER { get; set; }
    public string? IDENTTYPE { get; set; }
    public string? NAME { get; set; }
    public string? MAIDENNAME { get; set; }
    public string? FIRSTNAME { get; set; }
    public string? ADDRESS1 { get; set; }
    public string? ADDRESS2 { get; set; }
    public string? CITY { get; set; }
    public string? STATE { get; set; }
    public string? POSTALCODE { get; set; }
    public string? COUNTRY { get; set; }
    public DateTime? BIRTHDATE { get; set; }
    public byte? PATROW { get; set; }
    public string? INSCOVERAGECODE { get; set; }
    public DateTime? ISSUECARDDATE { get; set; }
    public DateTime? EXPIRACARDDATE { get; set; }
    public string? AFFILCTRLKEY { get; set; }
    public string? STATUSCODE { get; set; }
    public int? MANAGAGENCY { get; set; }
    public string? MANAGADMIN { get; set; }
    public string? MANAGCODE { get; set; }
    public string? HCIDENT { get; set; }
    public byte? HCVALIDRIGHTS { get; set; }
    public string? HCGUARANTEES { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_ACTS
{
    public int ACTID { get; set; }
    public int? BUID { get; set; }
    public int? CATALOGID { get; set; }
    public string ACTCODE { get; set; } = string.Empty;
    public int ACTCREDATE { get; set; }
    public DateTime? ACTSSOCREDATE { get; set; }
    public string? ACTCHAPTER { get; set; }
    public string? SUBCHAPTER { get; set; }
    public int? COEFFICIENT { get; set; }
    public string? ACTCODEAFF { get; set; }
    public string? ACTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public byte? PRIORAGREEMENT { get; set; }
    public byte? REFUND100 { get; set; }
    public short? MAXNUMOFACTS { get; set; }
    public byte? SPECIFICRULENB { get; set; }
    public byte? MEDREFIND { get; set; }
    public byte? RESERVEDACTS { get; set; }
    public byte? BIOINITIATIVE { get; set; }
    public byte? TECCONTINGENCY { get; set; }
    public byte? MEDREFOPP { get; set; }
    public byte? BLOODTEST { get; set; }
    public string? ICRCODE { get; set; }
    public int? DEFACTNB { get; set; }
    public byte? TRANSMITEDACT { get; set; }
    public string? HOSTTEXT { get; set; }
    public byte? CALCMODE { get; set; }
    public byte? ACTNATURE { get; set; }
    public short? NFIRSTKMFREE { get; set; }
    public DateTime? APPLICDATE { get; set; }
    public DateTime? EXPIRADATE { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_BILL_TESTS
{
    public int BILLTESTID { get; set; }
    public int? BUID { get; set; }
    public string? TESTCODE { get; set; }
    public int? TESTCREDATE { get; set; }
    public int? RULEID { get; set; }
    public byte? TESTTYPE { get; set; }
    public DateTime? APPLICDATE { get; set; }
    public DateTime? EXPIRADATE { get; set; }
    public byte? COLLECTTYPE { get; set; }
    public byte? BILLCALCMODE { get; set; }
    public int? NBACT { get; set; }
    public int? NBBILLU { get; set; }
    public byte? ACTTFEES { get; set; }
    public byte? TRANSMITTEDTEST { get; set; }
    public string? ICRCODE { get; set; }
    public string? BILLHOSTTEXT { get; set; }
    public string? EXTERNALLABNUM { get; set; }
    public byte? SPECIALITY { get; set; }
    public byte? TARIFFAREA { get; set; }
    public string? LISTESTCODE { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_ORGANISATS
{
    public int ORGID { get; set; }
    public int? CINID { get; set; }
    public int? GROUPID { get; set; }
    public string ORGCODE { get; set; } = string.Empty;
    public int ORGCREDATE { get; set; }
    public string? ORGNAME { get; set; }
    public string? ADDRESS1 { get; set; }
    public string? ADDRESS2 { get; set; }
    public string? CITY { get; set; }
    public string? STATE { get; set; }
    public string? POSTALCODE { get; set; }
    public string? COUNTRY { get; set; }
    public string? TELEPHON { get; set; }
    public string? TELEPHON2 { get; set; }
    public string? FAX { get; set; }
    public string? EMAIL { get; set; }
    public string? NATIONALCODE { get; set; }
    public string? INFORMATION { get; set; }
    public int? REMINDERTIME1 { get; set; }
    public int? REMINDERTIME2 { get; set; }
    public int? REMINDERTIME3 { get; set; }
    public int? LEGALTIME { get; set; }
    public byte? MUTDECOMPT { get; set; }
    public int? GLODISCOUNT { get; set; }
    public byte? DISCOUNTCODE { get; set; }
    public int? DETDISCOUNT { get; set; }
    public byte? STATPERIODICITY { get; set; }
    public byte? STATPRINTOUT { get; set; }
    public byte? CANCELFACPRINT { get; set; }
    public byte? CANCELFSSPRINT { get; set; }
    public byte? PECPATIENT { get; set; }
    public byte? NBSTATCOPIES { get; set; }
    public byte? CUMULATIVEBILL { get; set; }
    public byte? SORTBYNAME { get; set; }
    public byte? TFEES { get; set; }
    public byte? FSSAFTERFCU { get; set; }
    public byte? SETTLEMENT { get; set; }
    public byte? B3EXCLUDED { get; set; }
    public string? CUSTOMERCODE { get; set; }
    public byte? CERTIFICATIONTOP { get; set; }
    public byte? FSSAFTERTELE { get; set; }
    public int? PECLOWERLIMIT { get; set; }
    public int? PECUPPERLIMIT { get; set; }
    public byte? ELECTRONICBILL { get; set; }
    public byte? ROWORBENEF { get; set; }
    public byte? CONTRACTTYPE { get; set; }
    public byte? SSOCONTRACT { get; set; }
    public int? MANAGAGENCY { get; set; }
    public string? STATUSCODE { get; set; }
    public int? CENTRECODE { get; set; }
    public byte? VERSION { get; set; }
    public byte? STANDARD { get; set; }
    public int? COMPLEMENTID { get; set; }
    public string? STATREPORT { get; set; }
    public string? LISORGCODE { get; set; }
    public string? LISTELEM1 { get; set; }
    public string? LISTELEM2 { get; set; }
    public byte? MEDICALNECESSITY { get; set; }
    public string? CONTACTNAME { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class DICT_ORGTYPES
{
    public byte ORGTYPE { get; set; }
    public string? ORGTYPETXT { get; set; }
    public byte? PECORDER { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class INVOICE_DETAILS
{
    public int INVDETAILID { get; set; }
    public int? CUSTOMERTYPE { get; set; }
    public string? LISINVNUMBER { get; set; }
    public string? INVNUMBER { get; set; }
    public int? LISPAYAMOUNT { get; set; }
    public int? TOTPAYAMOUNT { get; set; }
    public int? TFEESAMOUNT { get; set; }
    public int? DISCAMOUNT { get; set; }
    public int? FSSBASEAMOUNT { get; set; }
    public int? AMOUNTDUE { get; set; }
    public int? BALANCE { get; set; }
    public byte? REMINDLEVEL { get; set; }
    public DateTime? LASTREMINDDATE { get; set; }
    public int? STATPERIOD { get; set; }
    public byte? REFCURRENCY { get; set; }
    public int? COMPORGAMOUNTDUE { get; set; }
    public int? COMPORGLISPAYAMOUNT { get; set; }
    public int? COMPORGFSSBASEAMOUNT { get; set; }
    public int? COMPORGDISCAMOUNT { get; set; }
    public byte? ORGCOVERAGE { get; set; }
    public string? ESSNUMBER { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public byte? RECYCLINGSTATE { get; set; }
}

public class INVOICES
{
    public int INVOICEID { get; set; }
    public int? RISKID { get; set; }
    public int? CATALOGID { get; set; }
    public int? BUTARID { get; set; }
    public string ACCESSNUMBER { get; set; } = string.Empty;
    public int REQCREATIONDATE { get; set; }
    public byte? CATEGORY { get; set; }
    public DateTime? PRESCRIPTDATE { get; set; }
    public DateTime? CLOSINGDATE { get; set; }
    public DateTime? VISITDATE { get; set; }
    public byte? REQSTATUS { get; set; }
    public byte? BILLSTATUS { get; set; }
    public string? HCSTATUS { get; set; }
    public byte? EXEMPCODE { get; set; }
    public int? INSNATURE { get; set; }
    public byte? RIGHTORIGIN { get; set; }
    public string? SSOSTATUS { get; set; }
    public DateTime? WORKACCDATE { get; set; }
    public string? WORKACCIDENTNO { get; set; }
    public DateTime? PREGNENDDATE { get; set; }
    public byte? PRIORAGREECODE { get; set; }
    public DateTime? PRIORAGREEDATE { get; set; }
    public string? EMPLOYNAME { get; set; }
    public int? CHARGESAMOUNT { get; set; }
    public int? AMOUNTDUE { get; set; }
    public int? COLLECTAMOUNT { get; set; }
    public int? TRAVELNUMBER { get; set; }
    public int? TRAVELAMOUNT { get; set; }
    public int? TRANSAMOUNT { get; set; }
    public int? NONTRANSLISTEDAMOUNT { get; set; }
    public int? NONLISTEDAMOUNT { get; set; }
    public byte? REMOTETRANS { get; set; }
    public int? KILOMETERS { get; set; }
    public byte? NBOFCOLLECTIONS { get; set; }
    public int? NBOFIMPEG { get; set; }
    public byte? REFCURRENCY { get; set; }
    public byte? INVREADY { get; set; }
    public byte? INVCALCSTATUS { get; set; }
    public byte? INVALD { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public int? EXPENSEREASON { get; set; }
    public byte? PATIENTREFUND { get; set; }
    public DateTime LOGDATE { get; set; }
}

public class PAYMENT_COMMENTS
{
    public int PAYMENTID { get; set; }
    public byte PAYMENTSUBJECT { get; set; }
    public byte COMMENTTYPE { get; set; }
    public string? COMMENTTEXT { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class PAYMENT_DETAILS
{
    public int INVDETAILID { get; set; }
    public int PAYMENTID { get; set; }
    public int? PAYAMOUNT { get; set; }
    public DateTime REPARTDATE { get; set; }
    public byte? REFCURRENCY { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class PAYMENTS
{
    public int PAYMENTID { get; set; }
    public int? CASHID { get; set; }
    public DateTime PAYCREATIONDATE { get; set; }
    public DateTime PAYDATE { get; set; }
    public int? PAYAMOUNT { get; set; }
    public string? CREDITCARDNUM { get; set; }
    public DateTime? CARDEXPDATE { get; set; }
    public string? CARDHOLDERNAME { get; set; }
    public byte? REFCURRENCY { get; set; }
    public int? CANCELAMOUNT { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class STAT_COMMENTS
{
    public int STATID { get; set; }
    public byte STATCOMSUBJECT { get; set; }
    public byte COMMENTTYPE { get; set; }
    public string? COMMENTTEXT { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class STATEMENTS
{
    public int STATID { get; set; }
    public DateTime STATCREDATE { get; set; }
    public byte STATTYPE { get; set; }
    public byte STATCOUNTER { get; set; }
    public int STATBEGPERIOD { get; set; }
    public int STATENDPERIOD { get; set; }
    public int? AMOUNTDUE { get; set; }
    public byte STATSTATUS { get; set; }
    public byte? REMINDERLEVEL { get; set; }
    public byte? REFCURRENCY { get; set; }
    public string? STATNUMBER { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SUBREQUESTS_HC
{
    public string SUBREQNUMBER { get; set; } = string.Empty;
    public string? CODE { get; set; }
    public string? CODECLASS { get; set; }
    public byte? CODINGTYPE { get; set; }
    public string ACCESSNUMBER { get; set; } = string.Empty;
    public int REQCREATIONDATE { get; set; }
    public int? DISCIPLINE { get; set; }
    public DateTime? SUBREQSTATUSDATE { get; set; }
    public byte? SUBREQSTATUS { get; set; }
    public byte? REQEXTRACT { get; set; }
    public byte? MORPHOCODESEXIST { get; set; }
    public byte? WRRELEASE { get; set; }
    public byte? NBSPEC { get; set; }
    public short? NEXTNUMCOLO { get; set; }
    public byte MICRODONE { get; set; }
    public string? CYTOPATTERN { get; set; }
    public string? TECHNOTES { get; set; }
    public DateTime? CYTOREPCREDATE { get; set; }
    public byte? REFERISASKED { get; set; }
    public byte? ADDEDSTAINS { get; set; }
    public byte? RELEVANT { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public DateTime? FORMALINFIXDATE { get; set; }
}

public class SUBREQUESTS_MB
{
    public int SUBREQUESTID { get; set; }
    public int? COLLMATERIALID { get; set; }
    public int? COLLSOURCEID { get; set; }
    public int? COLLTECHNIQUEID { get; set; }
    public int? TOPOGRAPHYID { get; set; }
    public int? PROTOCOLID { get; set; }
    public string SUBREQUESTNUMBER { get; set; } = string.Empty;
    public DateTime SUBREQUESTCREDATE { get; set; }
    public DateTime? COLLECTIONDATE { get; set; }
    public DateTime? RECEIVEDDATE { get; set; }
    public byte? URGENT { get; set; }
    public byte? NORMALCYTOLOGY { get; set; }
    public DateTime? OPTVALDATE { get; set; }
    public byte? COMPLETED { get; set; }
    public byte? NEGATIVEEXAM { get; set; }
    public short? REFERASKED { get; set; }
    public string? REFERTO { get; set; }
    public short? STATUSSTART { get; set; }
    public short? NEXTAGARINDEX { get; set; }
    public short? NEXTORGANISMINDEX { get; set; }
    public byte? NOSOINQUIRY { get; set; }
    public byte? CONSOLIDATIONSTATUS { get; set; }
    public short? MANDATORYDECLARATION { get; set; }
    public DateTime? LASTREVIEWDATE { get; set; }
    public DateTime? LASTUPDTESTDATE { get; set; }
    public string? COLLSOURCETXT { get; set; }
    public string? COLLMATERIALTXT { get; set; }
    public string? COLLTECHNIQUETXT { get; set; }
    public string? TOPOGRAPHYTXT { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
    public byte? VALIDATIONSTATUS { get; set; }
    public short? PATHOGENICEXAM { get; set; }
}

public class DICT_TESTS_OCOM
{
    public int DICTTESTOCOMID { get; set; }
    public string COMMENTTEXT { get; set; } = string.Empty;
    public byte COMMENTTYPE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SUBREQMB_ACTIONS
{
    public int SUBACTIONMARKID { get; set; }
    public int? ACTIONMARKLINK { get; set; }
    public short ACTIONMARKTYPE { get; set; }
    public DateTime ACTIONMARKDATE { get; set; }
    public string ACTIONMARKUSERID { get; set; } = string.Empty;
    public string? ACTIONMARKDATA1 { get; set; }
    public string? ACTIONMARKDATA2 { get; set; }
    public string? ACTIONMARKDATA3 { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class THRESHOLD_DEPT
{
    public int THRESHOLDID { get; set; }
    public int DEPARTMENTID { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class THRESHOLD_LAB
{
    public int THRESHOLDID { get; set; }
    public int LABOID { get; set; }
    public byte? SOURCE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class SP_TESTS_DICT_TESTS
{
    public string SP_ACCESSNUMBER { get; set; } = string.Empty;
    public int SP_TESTORDER { get; set; }
    public int TESTID { get; set; }
}

public class SP_REQUESTS_DICT_DOCTORS
{
    public string SP_ACCESSNUMBER { get; set; } = string.Empty;
    public int DOCID { get; set; }
}

public class SP_REQUESTS_DICT_LOCATIONS
{
    public string SP_ACCESSNUMBER { get; set; } = string.Empty;
    public int LOCID { get; set; }
}

public class DICT_TESTS_PERF_ON_ADD_DATA_DICT_SAMPLES_TYPES
{
    public string SITECODE { get; set; } = string.Empty;
    public string TESTCODE { get; set; } = string.Empty;
    public byte URGENT { get; set; }
    public int SAMPTYPEID { get; set; }
}

public class DICT_TESTS_DICT_TESTS_PERF_ON_ADD_DATA
{
    public string SITECODE { get; set; } = string.Empty;
    public string TESTCODE { get; set; } = string.Empty;
    public byte URGENT { get; set; }
    public int TESTID { get; set; }
}

public class USER_FUNCTIONS
{
    public string USERID { get; set; } = string.Empty;
    public string FUNCTEXT { get; set; } = string.Empty;
    public byte FUNCTYPE { get; set; }
    public byte FUNCORDER { get; set; }
    public byte FUNCDEPTH { get; set; }
    public string? FUNCCOMMAND { get; set; }
    public string? FUNCALIAS { get; set; }
    public string? FUNCSHORTCUT { get; set; }
    public string? LOGUSERID { get; set; }
    public DateTime? LOGDATE { get; set; }
}

public class DICT_PAY_METHODS
{
    public int PAYMENTMETHODID { get; set; }
    public string PAYMENTMETHODCODE { get; set; } = string.Empty;
    public int PAYMENTMETHODCREDATE { get; set; }
    public byte PAYMENTTYPE { get; set; }
    public string? PAYMENTTEXT { get; set; }
    public string? FULLTEXT { get; set; }
    public byte? ACCOUNTJOU { get; set; }
    public byte? PRINTEDONLCLI { get; set; }
    public int? FIRSTITEMID { get; set; }
    public DateTime STARTVALIDDATE { get; set; }
    public DateTime? ENDVALIDDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

public class UNIX_REVIEW_COUNTERS
{
    public int ID { get; set; }
    public int? QUEUEINDEX { get; set; }
    public int? TOREVIEWCOUNT { get; set; }
    public DateTime LASTUPDATE { get; set; }
    public string LOGUSERID { get; set; } = string.Empty;
    public DateTime LOGDATE { get; set; }
}

#nullable restore